spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fromnow?autoReconnect=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&cacheDefaultTimezone=false
    username: root
    password: ${LOCAL_DB_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  cloud:
    azure:
      storage:
        blob:
          account-name: ${AZURE_ACCOUNT_NAME}
          account-key: ${AZURE_ACCOUNT_KEY}
          endpoint: ${AZURE_STORAGE_ENDPOINT}
          connection-string: ${AZURE_CONNECTION_STRING}

    gcp:
      storage:
        credentials:
          location: classpath:linen-radio-438510-m9-5b0964e71e0a.json
        project-id: linen-radio-438510-m9
        bucket: fromnow-dev-bucket

google:
  cloud:
    credentials:
      path: linen-radio-438510-m9-5b0964e71e0a.json

firebase:
  json:
    url: fromnow-34d51-firebase-adminsdk-fiy84-7b40c25669.json

logging:
  level:
    org:
    hibernate:
      SQL: DEBUG
    type:
      descriptor:
        sql:
          BasicBinder: TRACE

springdoc:
  packages-to-scan: com.knu.fromnow
  override-with-generic-response: true
  default-consumes-media-type: application/json;charset=UTF-8 # ?? ??? ??
  default-produces-media-type: application/json;charset=UTF-8 # ?? ??? ??
  swagger-ui:
    operations-sorter: method # operations ?? ??? HTTP Method ?
    tags-sorter: alpha # tag ?? ??? ??? ?
